// ⭐ This is the only file you need to edit day-to-day.
// Flip `imminent: true` on drop days to enable faster checking (via Railway worker).

export const sites = [
  {
    name: "SharedPour – T8KE",
    id: "sharedpour_t8ke",
    enabled: true,
    strategy: "shopify_collection",
    url: "https://sharedpour.com/collections/t8ke",
    intervalMinutes: 20,
    schedule: "working_hours_heavy",
    imminentIntervalMinutes: 2,
    imminent: false,
    alertOnNewProduct: true,
    alertOnRestock: true,
    alertOnSoldOut: true,
    filters: {
      titleContains: [],
      titleExcludes: [],
      vendorIs: [],
      productType: [],
      tags: [],
      minPriceDollars: null,
      maxPriceDollars: null,
      availableOnly: false,
    },
  },
  {
    name: "SharedPour – The Reveries",
    id: "sharedpour_reveries",
    enabled: true,
    strategy: "shopify_collection",
    url: "https://sharedpour.com",
    intervalMinutes: 20,
    schedule: "weekend_light_20_mins",
    imminentIntervalMinutes: 2,
    imminent: false,
    alertOnNewProduct: true,
    alertOnRestock: true,
    alertOnSoldOut: true,
    filters: {
      titleContains: ["Reveries"],
      titleExcludes: [],
      vendorIs: [],
      productType: [],
      tags: [],
      minPriceDollars: null,
      maxPriceDollars: null,
      availableOnly: false,
    },
  },
  {
    name: "Fountain Inn DC",
    id: "fountain_inn_dc",
    enabled: true,
    strategy: "shopify_collection",
    url: "https://shop.fountaininndc.com",
    intervalMinutes: 30,
    schedule: "weekend_light_20_mins",
    imminentIntervalMinutes: 2,
    imminent: false,
    alertOnNewProduct: true,
    alertOnRestock: true,
    alertOnSoldOut: true,
    filters: {
      titleContains: ["Reveries"],
      titleExcludes: [],
      vendorIs: [],
      productType: [],
      tags: [],
      minPriceDollars: null,
      maxPriceDollars: null,
      availableOnly: false,
    },
  },
  {
    name: "Bourbon Concierge",
    id: "bourbon_concierge",
    enabled: true,
    strategy: "shopify_collection",
    url: "https://thebourbonconcierge.com",
    intervalMinutes: 30,
    schedule: "weekend_light_20_mins",
    imminentIntervalMinutes: 2,
    imminent: false,
    alertOnNewProduct: true,
    alertOnRestock: true,
    alertOnSoldOut: true,
    filters: {
      titleContains: ["Reveries"],
      titleExcludes: [],
      vendorIs: [],
      productType: [],
      tags: [],
      minPriceDollars: null,
      maxPriceDollars: null,
      availableOnly: false,
    },
  },
  {
    // DISABLED — enable once you've confirmed the page is SSR and the button text appears in View Source.
    // If the page is JS-rendered, find the API call in DevTools → Network and use that URL instead.
    name: "Wild Turkey – Gold Foil Edition",
    id: "wild_turkey_gold_foil",
    enabled: false,
    strategy: "html_text_monitor",
    url: "https://www.wildturkeybourbon.com/en-us/products/",
    intervalMinutes: 30,
    schedule: "30",
    imminentIntervalMinutes: 5,
    imminent: false,
    alertOnNewProduct: false,
    alertOnRestock: true,
    alertOnSoldOut: false,
    filters: {},
    monitor: {
      anchorText: "Gold Foil",
      // First match wins — put the "buy" states before "SEE DETAILS"
      watchTexts: ["ADD TO CART", "BUY NOW", "BUY", "IN STOCK", "SEE DETAILS"],
      alertValues: ["ADD TO CART", "BUY NOW", "BUY", "IN STOCK"],
      windowChars: 3000,
    },
  },
  {
    // thereveries.co/shop embeds a Shopify Buy Button (collection 367215214747 on
    // shared-pour.myshopify.com). That collection is only published to the Buy Button
    // channel — not the Online Store — so the REST /products.json API returns empty.
    // The Storefront API with the public token from the page JS sees it correctly.
    name: "The Reveries – Official Shop",
    id: "reveries_official",
    enabled: true,
    strategy: "shopify_storefront",
    url: "https://www.thereveries.co/shop",
    storefrontDomain: "shared-pour.myshopify.com",
    storefrontAccessToken: "9238d5183f01462f5ba642447811ebb8",
    storefrontCollectionId: "367215214747",
    intervalMinutes: 30,
    schedule: "weekend_light_20_mins",
    imminentIntervalMinutes: 2,
    imminent: false,
    alertOnNewProduct: true,
    alertOnRestock: true,
    alertOnSoldOut: true,
    filters: {},
  },
  {
    // Disabled — was watching thereveries.co/shop?format=json which returns page
    // metadata only (no products). reveries_official now covers the real data source.
    name: "The Reveries – Change Monitor",
    id: "reveries_official_monitor",
    enabled: false,
    strategy: "squarespace_json_monitor",
    url: "https://www.thereveries.co/shop",
    intervalMinutes: 30,
    schedule: "5",
    imminentIntervalMinutes: 2,
    imminent: false,
    alertOnNewProduct: false,
    alertOnRestock: false,
    alertOnSoldOut: false,
    filters: {},
  },
];
