// ⭐ This is the only file you need to edit day-to-day.
// Flip `imminent: true` on drop days to enable faster checking (via Render worker).

export const sites = [
  {
    name: "SharedPour – T8KE",
    id: "sharedpour_t8ke",
    enabled: true,
    strategy: "shopify_collection",
    url: "https://sharedpour.com/collections/t8ke",
    intervalMinutes: 20,
    schedule: "15",
    imminentIntervalMinutes: 2,
    imminent: false,
    alertOnNewProduct: true,
    alertOnRestock: true,
    alertOnSoldOut: false,
    filters: {
      titleContains: [],
      titleExcludes: [],
      vendorIs: [],
      productType: [],
      tags: [],
      minPriceDollars: null,
      maxPriceDollars: null,
      availableOnly: false,
    },
  },
  {
    name: "SharedPour – The Reveries",
    id: "sharedpour_reveries",
    enabled: true,
    strategy: "shopify_collection",
    url: "https://sharedpour.com",
    intervalMinutes: 20,
    schedule: "15",
    imminentIntervalMinutes: 2,
    imminent: false,
    alertOnNewProduct: true,
    alertOnRestock: true,
    alertOnSoldOut: false,
    filters: {
      titleContains: ["Reveries"],
      titleExcludes: [],
      vendorIs: [],
      productType: [],
      tags: [],
      minPriceDollars: null,
      maxPriceDollars: null,
      availableOnly: false,
    },
  },
  {
    name: "Fountain Inn DC",
    id: "fountain_inn_dc",
    enabled: true,
    strategy: "shopify_collection",
    url: "https://shop.fountaininndc.com",
    intervalMinutes: 30,
    schedule: "bar_schedule_fi",
    imminentIntervalMinutes: 2,
    imminent: false,
    alertOnNewProduct: true,
    alertOnRestock: true,
    alertOnSoldOut: false,
    filters: {
      titleContains: ["Reveries"],
      titleExcludes: [],
      vendorIs: [],
      productType: [],
      tags: [],
      minPriceDollars: null,
      maxPriceDollars: null,
      availableOnly: false,
    },
  },
  {
    name: "Bourbon Concierge",
    id: "bourbon_concierge",
    enabled: true,
    strategy: "shopify_collection",
    url: "https://thebourbonconcierge.com",
    intervalMinutes: 30,
    schedule: "5",
    imminentIntervalMinutes: 2,
    imminent: false,
    alertOnNewProduct: true,
    alertOnRestock: true,
    alertOnSoldOut: false,
    filters: {
      titleContains: ["Reveries"],
      titleExcludes: [],
      vendorIs: [],
      productType: [],
      tags: [],
      minPriceDollars: null,
      maxPriceDollars: null,
      availableOnly: false,
    },
  },
  {
    name: "The Reveries – Official Shop",
    id: "reveries_official",
    enabled: true,
    strategy: "reveries_squarespace",
    url: "https://www.thereveries.co/shop",
    intervalMinutes: 30,
    schedule: "15",
    imminentIntervalMinutes: 2,
    imminent: false,
    alertOnNewProduct: true,
    alertOnRestock: false,
    alertOnSoldOut: false,
    filters: {
      titleContains: [],
      titleExcludes: [],
      vendorIs: [],
      productType: [],
      tags: [],
      minPriceDollars: null,
      maxPriceDollars: null,
      availableOnly: false,
    },
  },
];
